"""Single entry point for the federated-EHR experiment: train and test jobs.

This is the only launcher. It submits SLURM jobs for the two things the paper
table needs -- training a regime (``train.py``) and scoring rare-code ML
efficacy across regimes (``test2_rare_efficacy.py``) -- and nothing else.
Building the cohort cache (``utils/cohort.py``) deliberately does NOT hang off
this file: it runs once, and mixing a one-off data-prep step into the launcher
is how a "just rerun it" ends up silently re-splitting the data underneath a
half-finished comparison.

    # one training regime (submits, prints the job id)
    python examples/fedpyhealth/main.py train --regime fedavg --profile full

    # the whole table: four regimes, then Test 2 chained after they all finish
    python examples/fedpyhealth/main.py all --profile full \
        --cohort-cache $FEDCOHORT_CACHE/strat8

    # see the generated sbatch script without submitting anything
    python examples/fedpyhealth/main.py train --regime local --dry-run

Unrecognised flags pass straight through to the underlying script, so anything
``train.py`` or ``test2_rare_efficacy.py`` accepts still works::

    python examples/fedpyhealth/main.py train --profile full --n-rounds 100

Every job writes to ``_outputs/`` (gitignored): SLURM logs under
``_outputs/slurm/``, checkpoints and synthetic data under
``_outputs/<run_name>_save/``, one file per run under
``_outputs/results/runs/``, and test scores under ``_outputs/results/tests/``.
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import time
from typing import List, Sequence, Tuple

from utils.cohort import DEFAULT_CACHE_DIR, FOLDS, load_manifest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SLURM_DIR = "_outputs/slurm"
LAUNCH_DIR = "_outputs/slurm/launch"

ACCOUNT = "bgyw-delta-gpu"
PARTITION = "gpuA100x4"
# Measured at ~1.0 core in use; see the --cpus help text.
CPUS_PER_TASK = 16
MAIL_USER = "zd16@illinois.edu"

REGIMES = ("fedavg", "fedavg_ft", "centralized", "local")

# Per-job resources. Both profiles load the FULL eICU (a tiny run is small in
# compute, not in data), so both need the same memory; only the wall clock
# differs. Tiny's own training is ~5-10 min, but the dataset load in front of it
# is the same fixed cost every run pays -- hence 2h rather than 20 minutes.
PROFILE_RESOURCES = {
    "tiny": {"time": "02:00:00", "mem": "128g"},
    "full": {"time": "48:00:00", "mem": "128g"},
}
# Test 1 only rebuilds frames and bootstraps; Test 2 trains a classifier per
# hospital per mask fold, so it gets the longer window.
TEST_RESOURCES = {
    "test1": {"time": "03:00:00", "mem": "128g"},
    "test2": {"time": "06:00:00", "mem": "128g"},
}

SBATCH_TEMPLATE = """#!/bin/bash
#SBATCH --mem={mem}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task={cpus}
#SBATCH --partition={partition}
#SBATCH --account={account}
#SBATCH --job-name={job_name}
#SBATCH --time={time}
#SBATCH --gpus-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=closest
#SBATCH --mail-user={mail_user}
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output={slurm_dir}/%x-%j.out

# Generated by examples/fedpyhealth/main.py -- edit the launcher, not this file.
set -euo pipefail

source .venv/bin/activate

{command}
"""


def _build_arg_parser() -> argparse.ArgumentParser:
    # Shared flags live on a parent parser so they are accepted BOTH before and
    # after the subcommand. Defined only at the top level, `main.py train
    # --dry-run` would silently forward --dry-run to train.py and submit for
    # real. They default to SUPPRESS so an unset flag on the subparser does not
    # clobber the same flag given at the top level.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--dry-run", action="store_true",
                        default=argparse.SUPPRESS,
                        help="print the sbatch script(s) instead of submitting")
    common.add_argument("--time", default=argparse.SUPPRESS,
                        help="override the SBATCH wall clock")
    common.add_argument("--mem", default=argparse.SUPPRESS,
                        help="override the SBATCH memory")
    common.add_argument("--cpus", default=argparse.SUPPRESS,
                        help="override --cpus-per-task (default 16). Measured: "
                             "the pipeline uses ~1.0 core (TotalCPU 14:54:44 "
                             "over 14:52:22 wall on 16 CPUs), and the loader "
                             "runs num_workers=0, so 16 buys nothing. CPUs bill "
                             "at 62.5 each on gpuA100x4 -- 16 of them cost about "
                             "as much as the GPU.")
    common.add_argument("--partition", default=argparse.SUPPRESS,
                        help=f"override the SBATCH partition (default "
                             f"{PARTITION}). 'gpuA100x4-preempt' is the same "
                             f"A100 hardware at half the billing weight and a "
                             f"far shorter queue, at the cost of REQUEUE on "
                             f"preemption -- safe here because every regime "
                             f"checkpoints per round/epoch and --resume is on "
                             f"by default.")
    common.add_argument("--account", default=argparse.SUPPRESS,
                        help=f"override the SBATCH account (default {ACCOUNT})")
    common.add_argument("--cohort-cache", default=argparse.SUPPRESS,
                        help="cohort cache every job in this invocation reads")
    common.add_argument("--skip-cohort-check", action="store_true",
                        default=argparse.SUPPRESS,
                        help="submit without pre-flighting the cohort cache")

    p = argparse.ArgumentParser(
        description=__doc__ or "",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        parents=[common],
    )
    sub = p.add_subparsers(dest="job", required=True)

    train = sub.add_parser("train", parents=[common],
                           help="train one regime (train.py)")
    train.add_argument("--regime", choices=REGIMES, default="fedavg")
    train.add_argument("--profile", choices=sorted(PROFILE_RESOURCES),
                       default="full")

    every = sub.add_parser(
        "all", parents=[common],
        help="train all four regimes, then chain the tests after them")
    every.add_argument("--profile", choices=sorted(PROFILE_RESOURCES),
                       default="full")

    for name, helptext in (
        ("test1", "prevalence fidelity (test1_prevalence.py)"),
        ("test2", "pooled rare-code ML efficacy / TSTR (test2_rare_efficacy.py)"),
    ):
        t = sub.add_parser(name, parents=[common], help=helptext)
        t.add_argument("--after", default=None,
                       help="colon-separated job ids to wait for "
                            "(--dependency=afterok:...)")

    sub.add_parser("status", parents=[common],
                   help="how far along are my jobs (queue state + progress)")
    return p


# --------------------------------------------------------------------------- #
# Status                                                                       #
# --------------------------------------------------------------------------- #
# Progress markers the training script prints. Rounds/epochs are the only
# honest progress signal: a job can sit at "RUNNING" for an hour while it does
# nothing but load eICU.
PROGRESS_RE = (
    re.compile(r"round (\d+)/(\d+)", re.I),
    re.compile(r"Epoch (\d+)/(\d+)"),
    re.compile(r"\.\.\.(\d+)/(\d+)"),          # cohort.py's eICU walk
    re.compile(r"Epoch (\d+):"),
)

# What the job is actually DOING, in order. A job can sit at RUNNING for an
# hour inside one of these, and which one it is changes what "slow" means:
# training slowly is normal, still generating after an hour is not.
PHASES = (
    ("saved",       re.compile(r"Saved synthetic data ->|OK: all \d+ cached|"
                               r"^Wrote ", re.M)),
    ("evaluating",  re.compile(r"=== (Global|Per-client) metrics|"
                               r"classifiers to train:")),
    ("generating",  re.compile(r"Generated \d+ synthetic|generated \d+ synthetic")),
    ("verifying",   re.compile(r"Verifying: rebuilding")),
    ("training",    re.compile(r"Regime: |Centralized: |Local-only: |FedAvg: ")),
    ("writing",     re.compile(r"^Cohort \(|^  \[\d+\] \d+ patients", re.M)),
    ("walking eICU", re.compile(r"Walking samples")),
    ("loading",     re.compile(r"Loading eICU|Cohort '")),
)

# How a finished log ended. Ordered: a traceback anywhere beats a success line
# printed before it.
# TIMEOUT is checked BEFORE FAILED: SLURM logs a wall-clock kill as
# "slurmstepd: error", which would otherwise read as a bug in the code. The two
# call for opposite responses -- resubmit with --resume vs. fix something.
OUTCOME_RE = (
    ("TIMEOUT", re.compile(r"DUE TO TIME LIMIT|CANCELLED AT")),
    ("FAILED",  re.compile(r"Traceback \(most recent call last\)|"
                           r"slurmstepd: error|"
                           r"^(?:\w+Error|Error)", re.M)),
    ("done",    re.compile(r"Saved synthetic data ->|OK: all \d+ cached|"
                           r"^Wrote .*\.json", re.M)),
)


# Trouble a job can hit while still reporting RUNNING. A run that OOMs on one
# client, or retries a NaN loss forever, keeps its SLURM state and burns the
# rest of its wall clock producing nothing -- so "RUNNING" alone is not health.
TROUBLE_RE = (
    ("CUDA OOM",       re.compile(r"CUDA out of memory|"
                                  r"torch\.cuda\.OutOfMemoryError")),
    ("traceback",      re.compile(r"Traceback \(most recent call last\)")),
    ("NaN loss",       re.compile(r"loss=nan|loss=inf", re.I)),
    ("NCCL/GPU error", re.compile(r"NCCL error|CUDA error|device-side assert")),
)

# A pending job whose dependency can never be met will sit in the queue until
# the wall clock runs out. SLURM does not clean these up; only you can.
ZOMBIE_REASONS = ("DependencyNeverSatisfied", "JobHeldUser", "JobHeldAdmin")


def _print_table(header: Sequence[str], rows: Sequence[Sequence]) -> None:
    """Left-aligned fixed-width table (no dependency on results.py)."""
    widths = [max(len(str(h)), *(len(str(r[i])) for r in rows)) if rows
              else len(str(h)) for i, h in enumerate(header)]
    print("  ".join(str(h).ljust(w) for h, w in zip(header, widths)))
    print("-" * (sum(widths) + 2 * len(header)))
    for r in rows:
        print("  ".join(str(c).ljust(w) for c, w in zip(r, widths)))


def _elapsed_seconds(text: str) -> float:
    """Parse SLURM elapsed ('1-02:03:04', '11:23:06', '4:07') into seconds."""
    days, _, rest = text.partition("-")
    if not rest:
        days, rest = "0", days
    parts = [float(x) for x in rest.split(":")]
    while len(parts) < 3:
        parts.insert(0, 0.0)
    h, m, s = parts
    return float(days) * 86400 + h * 3600 + m * 60 + s


def _progress(log_path: str):
    """Last (done, total) progress marker in a job log, or (done, None)."""
    tail = _tail(log_path, 200_000)
    if not tail:
        return None
    for rx in PROGRESS_RE:
        hits = rx.findall(tail)
        if hits:
            last = hits[-1]
            # findall yields a tuple per match only when the pattern has >1
            # group; with one group it yields a plain string, and last[0] would
            # take its first CHARACTER ("51" -> 5).
            if isinstance(last, tuple):
                return int(last[0]), int(last[1])
            return int(last), _total_epochs(tail)
    return None


def _total_epochs(tail: str):
    """Epoch budget from the regime banner, so a bare 'Epoch N:' gets an ETA."""
    m = re.search(r"(\d+) epochs", tail)
    return int(m.group(1)) if m else None


def _tail(log_path: str, nbytes: int = 400_000) -> str:
    """Last ``nbytes`` of a log. These reach hundreds of MB with progress bars."""
    if not os.path.exists(log_path):
        return ""
    with open(log_path, "rb") as fh:
        fh.seek(0, os.SEEK_END)
        fh.seek(max(0, fh.tell() - nbytes))
        return fh.read().decode("utf-8", "replace")


def _phase(tail: str) -> str:
    """Which stage the job has most recently reached."""
    for name, rx in PHASES:
        if rx.search(tail):
            return name
    return ""


def _outcome(tail: str) -> str:
    """How a log that is no longer running ended."""
    for name, rx in OUTCOME_RE:
        if rx.search(tail):
            return name
    return "ended early"


def _hospital_progress(tail: str):
    """For the local regime: which hospital of how many is training now."""
    seen = re.findall(r"training hospital (\S+)", tail)
    total = re.search(r"local-only -- (\d+) independent models", tail)
    if not seen or not total:
        return None
    return len(dict.fromkeys(seen)), int(total.group(1))


def _trouble(tail: str) -> List[str]:
    """Every trouble marker present in a running job's recent output."""
    return [name for name, rx in TROUBLE_RE if rx.search(tail)]


def _fmt_start(raw: str) -> str:
    """SLURM's estimated start ('2026-08-13T02:52:02') as '~29h out'."""
    if not raw or raw in ("N/A", "Unknown"):
        return ""
    try:
        start = time.mktime(time.strptime(raw, "%Y-%m-%dT%H:%M:%S"))
    except ValueError:
        return ""
    hours = (start - time.time()) / 3600
    if hours < 0:
        return "starting"
    return f"~{hours:.0f}h out" if hours < 48 else f"~{hours / 24:.1f}d out"


def _print_zombies(zombies: Sequence[Sequence[str]]) -> None:
    """Pending jobs that will never run, with the command to clear them."""
    if not zombies:
        return
    print("\nqueued but will NEVER run -- cancel these:")
    for jid, name, reason in zombies:
        print(f"  {jid}  {name}  ({reason})")
    print(f"\n  scancel {' '.join(z[0] for z in zombies)}")


def _print_finished(live: Sequence[str], limit: int = 8) -> None:
    """Show recently-ended jobs and how they ended.

    squeue forgets a job the moment it leaves the queue, which is exactly when
    you most want to know what happened to it -- a run that died at hour 12 and
    one that finished cleanly look identical from the queue (both absent).
    """
    logs = []
    for path in glob.glob(os.path.join(SLURM_DIR, "*.out")):
        stem = os.path.basename(path)[:-4]
        name, _, jid = stem.rpartition("-")
        if jid in live:
            continue                      # already in the running table above
        logs.append((os.path.getmtime(path), jid, name or stem, path))
    if not logs:
        return

    logs.sort(reverse=True)
    rows = []
    for mtime, jid, name, path in logs[:limit]:
        tail = _tail(path)
        age = (time.time() - mtime) / 3600
        rows.append([jid, name[:26], _outcome(tail), _phase(tail) or "-",
                     f"{age:.1f}h ago" if age < 48 else f"{age / 24:.0f}d ago"])
    print(f"\nrecently ended ({len(logs)} log(s) in {SLURM_DIR}):")
    _print_table(["job", "name", "outcome", "reached", "when"], rows)
    failed = [r for r in rows if r[2] in ("FAILED", "TIMEOUT")]
    for r in failed:
        print(f"  tail -50 {SLURM_DIR}/{r[1]}-{r[0]}.out    # {r[2]}")


def cmd_status() -> None:
    """Print queue state plus per-job progress and a finish estimate."""
    try:
        out = subprocess.run(
            ["squeue", "-u", os.environ.get("USER", ""), "-h",
             "-o", "%i|%j|%T|%M|%R|%S"],
            capture_output=True, text=True, timeout=30, check=True).stdout
    except Exception as exc:  # noqa: BLE001
        sys.exit(f"could not run squeue: {exc}")

    jobs = [ln.split("|") for ln in out.splitlines() if ln.strip()]
    live = {jid for jid, *_ in jobs}
    if not jobs:
        print("nothing in the queue.")
    else:
        rows, zombies, sick = [], [], []
        for jid, name, state, elapsed, reason, start in jobs:
            phase, prog, eta = "", "", ""
            if state != "RUNNING" and any(z in reason for z in ZOMBIE_REASONS):
                zombies.append([jid, name, reason])
            if state == "RUNNING":
                log_path = os.path.join(SLURM_DIR, f"{name}-{jid}.out")
                big_tail = _tail(log_path, 2_000_000)
                phase = _phase(big_tail)
                hit = _progress(log_path)
                if hit and hit[1]:
                    done, total = hit
                    prog = f"{done}/{total}"
                    secs = _elapsed_seconds(elapsed)
                    if done:
                        remaining = secs * (total - done) / done
                        eta = f"~{remaining / 3600:.1f}h left"
                elif hit:
                    prog = f"epoch {hit[0]}"
                # The local regime restarts its epoch count per hospital, so the
                # epoch number alone says nothing about how far along it is.
                if "local" in name:
                    hp = _hospital_progress(big_tail)
                    if hp:
                        prog = f"hosp {hp[0]}/{hp[1]}, {prog}"
                        eta = "(uneven: big hospitals first)"
                if not phase and not prog:
                    prog = "(no output yet)"
                hits = _trouble(big_tail)
                if hits:
                    sick.append([jid, name, ", ".join(hits)])
                    eta = f"!! {hits[0]}"
            note = eta
            if state != "RUNNING":
                note = " ".join(x for x in (reason, _fmt_start(start)) if x)
            rows.append([jid, name[:26], state, elapsed, phase, prog, note])
        _print_table(["job", "name", "state", "elapsed", "phase", "progress",
                      "note"], rows)
        if sick:
            print("\ntrouble in a RUNNING job (state alone won't show this):")
            for jid, name, hits in sick:
                print(f"  {jid}  {name}: {hits}")
                print(f"    grep -aE 'Error|Traceback|out of memory' "
                      f"{SLURM_DIR}/{name}-{jid}.out | tail -20")
        _print_zombies(zombies)

    _print_finished(live)

    # Finished work is invisible to squeue, so show what has landed on disk.
    runs = sorted(glob.glob("_outputs/results/runs/*.json"))
    tests = sorted(glob.glob("_outputs/results/tests/*.json"))
    print(f"\nresults on disk: {len(runs)} run(s)"
          f"{', ' + ', '.join(os.path.basename(t) for t in tests) if tests else ''}")
    for r in runs:
        print(f"  {os.path.basename(r)}")
    if runs and not tests:
        print("  (no test scores yet -- they run after all four regimes finish)")


def preflight_cohort(path: str) -> None:
    """Fail in a second, here, rather than minutes into a queued GPU job.

    Catches the expensive mistakes: no cache at that path, a cache missing one
    of its 24 Parquet files, or one built on the eICU dev subset.
    """
    manifest = load_manifest(path)          # raises with a pointed message
    hospitals = manifest["hospitals"]

    if manifest.get("dev"):
        sys.exit(
            f"{path} was built on the eICU DEV subset (dev=true), so its "
            "hospital sizes and rare codes are not representative. Rebuild it "
            "without --dev before running an experiment."
        )
    missing = [f"{hid}.{fold}.parquet" for hid in hospitals for fold in FOLDS
               if not os.path.exists(os.path.join(path, f"{hid}.{fold}.parquet"))]
    if missing:
        sys.exit(f"{path} is incomplete -- missing {len(missing)} fold files, "
                 f"e.g. {missing[:3]}. Rebuild it with utils/cohort.py.")

    per = manifest["per_hospital"]
    totals = {f: sum(per[h][f"n_{f}"] for h in hospitals) for f in FOLDS}
    n_all = sum(totals.values())
    print(f"cohort {manifest.get('cohort_name', '?')} ({path})")
    print(f"  {len(hospitals)} hospitals, {n_all} patients: " + " / ".join(
        f"{totals[f]} {f} ({totals[f] / max(1, n_all):.3f})" for f in FOLDS))
    print(f"  ids: {', '.join(hospitals)}")


def with_cohort(passthrough: Sequence[str], cohort_cache: str) -> List[str]:
    """Add ``--cohort-cache`` unless the caller already passed one."""
    if any(a.startswith("--cohort-cache") for a in passthrough):
        return list(passthrough)
    return list(passthrough) + ["--cohort-cache", cohort_cache]


# Knobs that change what a run *is*. train.py normally encodes these into the
# run name itself; since we pass an explicit --run-name, we have to fold any
# override back in, or two runs differing only in --n-rounds would share a name
# and clobber each other's checkpoints and results.
# --num-synth is deliberately NOT here. It changes only how many patients are
# generated from an already-trained model, so folding it into the name would
# fork the save dir and force a full retrain just to re-generate at a different
# count. Left out, a re-run with a bigger --num-synth finds the checkpoint,
# skips training entirely, and only regenerates. This also matches train.py's
# own make_run_name, which does not encode it either.
NAME_AFFECTING = ("--n-rounds", "--local-epochs", "--ft-epochs", "--weighting",
                  "--metrics")


def run_name_for(regime: str, profile: str, cohort_file: str,
                 passthrough: Sequence[str]) -> str:
    """Deterministic run name, so the launcher knows the save dir up front.

    Chaining the tests onto training requires knowing where the training run
    will put its output *before* it starts. train.py derives its own name from
    the resolved config, which the launcher cannot see, so the launcher supplies
    the name instead and both sides agree by construction.
    """
    cohort = os.path.basename(str(cohort_file).rstrip("/"))
    name = f"{regime}_{profile}_{cohort}"
    for i, arg in enumerate(passthrough):
        if arg in NAME_AFFECTING and i + 1 < len(passthrough):
            name += f"_{arg.lstrip('-').replace('-', '')}{passthrough[i + 1]}"
        elif arg.startswith(tuple(f"{k}=" for k in NAME_AFFECTING)):
            key, val = arg.split("=", 1)
            name += f"_{key.lstrip('-').replace('-', '')}{val}"
    return name


def save_dir_for(run_name: str) -> str:
    """Where train.py will persist that run (must match train.py's save_dir)."""
    return f"_outputs/{run_name}_save"


def record_run(job_id: str, run_name: str, dry_run: bool) -> None:
    """Append the launched job to the experiment log.

    Done here because the launcher is the only place that knows both the job id
    and the run name; leaving it to the user means the log is only as complete
    as their discipline, which is exactly when a log stops being useful.
    """
    if dry_run or job_id == "DRYRUN":
        return
    try:
        subprocess.run(
            ["python", "examples/fedpyhealth/exp_log.py", "record",
             "--job-id", job_id, "--run-name", run_name],
            check=True, capture_output=True, text=True,
        )
        print(f"  logged {run_name} (job {job_id})")
    except Exception as exc:  # noqa: BLE001 - logging must never sink a launch
        print(f"  WARNING: could not log job {job_id}: {exc}. The job IS "
              f"submitted; record it by hand with exp_log.py record.")


def render(job_name: str, command: str, time: str, mem: str,
           partition: str = None, account: str = None, cpus: str = None) -> str:
    """Fill the sbatch template for one job."""
    return SBATCH_TEMPLATE.format(
        mem=mem, partition=partition or PARTITION, account=account or ACCOUNT,
        cpus=cpus or CPUS_PER_TASK, job_name=job_name,
        time=time, mail_user=MAIL_USER, slurm_dir=SLURM_DIR, command=command,
    )


def submit(job_name: str, script: str, dry_run: bool,
           depends_on: str = None) -> str:
    """Write the job script and submit it; return the job id ('DRYRUN' if not).

    The script is kept on disk under ``_outputs/slurm/launch/`` so a submitted
    job stays inspectable after the fact -- what actually ran, not what the
    launcher would generate today.
    """
    os.makedirs(SLURM_DIR, exist_ok=True)
    os.makedirs(LAUNCH_DIR, exist_ok=True)
    path = os.path.join(LAUNCH_DIR, f"{job_name}.sbatch")
    with open(path, "w") as fh:
        fh.write(script)

    cmd = ["sbatch", "--parsable"]
    if depends_on:
        cmd.append(f"--dependency=afterok:{depends_on}")
    cmd.append(path)

    if dry_run:
        print(f"--- {path}\n{script}")
        print(f"[dry-run] would run: {' '.join(cmd)}\n")
        return "DRYRUN"

    job_id = subprocess.check_output(cmd, text=True).strip()
    dep = f" (after {depends_on})" if depends_on else ""
    print(f"submitted {job_name}: job {job_id}{dep}  -> {SLURM_DIR}/{job_name}-{job_id}.out")
    return job_id


def _flag_value(argv: Sequence[str], flag: str) -> str:
    """Value of ``--flag v`` or ``--flag=v`` in ``argv``, or None if absent."""
    for i, a in enumerate(argv):
        if a == flag and i + 1 < len(argv):
            return argv[i + 1]
        if a.startswith(f"{flag}="):
            return a.split("=", 1)[1]
    return None


def _strip_flag(argv: Sequence[str], flag: str,
                has_value: bool = True) -> List[str]:
    """``argv`` without ``--flag``, in either spelling.

    ``has_value=False`` for store_true/store_false flags, which have no
    following token to drop -- eating one would silently swallow the next
    flag's value.
    """
    out, skip = [], False
    for a in argv:
        if skip:
            skip = False
            continue
        if a == flag:
            skip = has_value
            continue
        if a.startswith(f"{flag}="):
            continue
        out.append(a)
    return out


def train_job(regime: str, profile: str, passthrough: Sequence[str],
              args, cohort_file: str) -> Tuple[str, str]:
    """Submit one training regime. Returns ``(job_id, run_name)``."""
    res = PROFILE_RESOURCES[profile]
    run_name = run_name_for(regime, profile, cohort_file, passthrough)
    # --fold is the TESTS' spelling of the reporting fold; train.py calls the
    # same thing --eval-fold. Translate rather than pass it through, so one
    # `main.py all --fold test` reaches both sides instead of killing the four
    # training jobs on an unrecognised argument. See fold_for_tests().
    fold = _flag_value(passthrough, "--fold")
    passthrough = _strip_flag(passthrough, "--fold")
    if fold and _flag_value(passthrough, "--eval-fold") is None:
        passthrough = list(passthrough) + ["--eval-fold", fold]
    # --resume unless the caller already said something about it. A `full` run
    # books the partition maximum (48h) and can still be killed by the wall
    # clock; without this, resubmitting the same command silently restarts from
    # round 0 rather than continuing, which cost 12h on job 21095176. It is safe
    # to default on: run_fedavg refuses a checkpoint whose fingerprint (client
    # sizes + split sha) does not match, so a checkpoint from another cohort
    # raises instead of being resumed into.
    resume = [] if "--resume" in passthrough else ["--resume"]
    command = (f"python examples/fedpyhealth/train.py --profile {profile} "
               f"--regime {regime} --run-name {run_name} "
               f"{' '.join(list(passthrough) + resume)}").strip()
    script = render(
        job_name=f"fed-{regime}-{profile}",
        command=command,
        time=args.time or res["time"],
        mem=args.mem or res["mem"],
        partition=getattr(args, "partition", None),
        account=getattr(args, "account", None),
        cpus=getattr(args, "cpus", None),
    )
    job_id = submit(f"fed-{regime}-{profile}", script, args.dry_run)
    record_run(job_id, run_name, args.dry_run)
    return job_id, run_name


# Knobs only train.py understands. main.py hands ONE passthrough to both the
# training and the scoring jobs, and the test scripts parse strictly, so a
# train-only flag reaching them is not ignored -- it kills the job on an
# unrecognised argument. `main.py all --n-rounds 80` submitted two scoring jobs
# that died the moment they started, hours later, with the training already
# done. Strip them instead.
TRAIN_ONLY_VALUED = (
    "--config", "--weighting", "--ft-epochs", "--n-rounds", "--local-epochs",
    "--num-synth", "--synth-per-hospital", "--metrics", "--ckpt-every",
    "--tb-logdir", "--log-every-epochs", "--run-name", "--es-patience",
    "--es-min-steps", "--es-min-val-patients", "--es-fallback",
)
TRAIN_ONLY_BOOL = ("--resume", "--no-tb", "--no-early-stop")


def fold_for_tests(passthrough: Sequence[str]) -> Tuple[List[str], List[str]]:
    """Decide which real fold the scoring jobs compare against.

    train.py selects models on **val** (early stopping) and reports on **test**,
    so the tests must score on test too -- scoring on the fold the model was
    stopped on would quote a number it was tuned against. Both test scripts
    still default to ``--fold val`` on their own, from before early stopping
    existed, so the launcher passes it explicitly rather than relying on their
    default drifting into agreement.

    ``--eval-fold`` is train.py's spelling of the same choice and is not a flag
    the test scripts know, so it is translated here. Every other train-only knob
    (``TRAIN_ONLY_VALUED`` / ``TRAIN_ONLY_BOOL``) is simply dropped, since the
    test scripts parse strictly and would die on it.

    Args:
        passthrough: Unparsed args destined for the job command.

    Returns:
        ``(cleaned_passthrough, fold_args)`` -- append ``fold_args`` to the
        test command. An explicit ``--fold`` from the user always wins.
    """
    cleaned = list(passthrough)
    for flag in TRAIN_ONLY_VALUED:
        cleaned = _strip_flag(cleaned, flag)
    for flag in TRAIN_ONLY_BOOL:
        cleaned = _strip_flag(cleaned, flag, has_value=False)
    cleaned = _strip_flag(cleaned, "--eval-fold")
    if _flag_value(passthrough, "--fold") is not None:
        return cleaned, []                       # user already decided
    return cleaned, ["--fold",
                     _flag_value(passthrough, "--eval-fold") or "test"]


def test_job(which: str, passthrough: Sequence[str], args,
             depends_on: str = None) -> str:
    """Submit a scoring job. ``which`` is ``test1`` or ``test2``."""
    script_name = {"test1": "test1_prevalence.py",
                   "test2": "test2_rare_efficacy.py"}[which]
    res = TEST_RESOURCES[which]
    passthrough, fold_args = fold_for_tests(passthrough)
    command = (f"python examples/fedpyhealth/{script_name} "
               + " ".join(list(passthrough) + fold_args)).strip()
    script = render(
        job_name=f"fed-{which}",
        command=command,
        time=args.time or res["time"],
        mem=args.mem or res["mem"],
        partition=getattr(args, "partition", None),
        account=getattr(args, "account", None),
        cpus=getattr(args, "cpus", None),
    )
    return submit(f"fed-{which}", script, args.dry_run, depends_on=depends_on)


def main(argv: List[str] = None) -> None:
    args, passthrough = _build_arg_parser().parse_known_args(argv)
    # SUPPRESS defaults mean an unset shared flag is simply absent.
    args.dry_run = getattr(args, "dry_run", False)
    args.time = getattr(args, "time", None)
    args.mem = getattr(args, "mem", None)
    cohort_file = getattr(args, "cohort_cache", DEFAULT_CACHE_DIR)

    if os.path.abspath(os.getcwd()) != REPO_ROOT:
        sys.exit(f"run this from the repo root ({REPO_ROOT}) -- every path in "
                 "the generated job script is repo-relative")

    # A stray main.py flag reaching the training script means it was misparsed;
    # better to stop than to submit a job that dies on an unknown argument.
    stray = [a for a in passthrough
             if a in ("--dry-run", "--skip-cohort-check", "--time", "--mem",
                      "--partition", "--account", "--cpus")]
    if stray:
        sys.exit(f"internal: {stray} leaked into the job command -- refusing to "
                 "submit. This is a launcher bug, not a usage error.")

    if args.job == "status":
        cmd_status()
        return

    if not getattr(args, "skip_cohort_check", False):
        preflight_cohort(cohort_file)
    passthrough = with_cohort(passthrough, cohort_file)

    if args.job == "train":
        train_job(args.regime, args.profile, passthrough, args, cohort_file)

    elif args.job == "all":
        submitted = [train_job(r, args.profile, passthrough, args, cohort_file)
                     for r in REGIMES]
        ids = [job_id for job_id, _ in submitted]
        dep = ":".join(ids)

        # Both tests read each run's synthetic.json, so they wait for all four.
        # The launcher assigned the run names, so it can build the --run specs
        # itself instead of asking the user to copy them out of four logs.
        run_specs: List[str] = []
        for (_, run_name), regime in zip(submitted, REGIMES):
            run_specs += ["--run", f"{regime}={save_dir_for(run_name)}"]
        print()
        for which in ("test1", "test2"):
            test_job(which, list(passthrough) + run_specs, args, depends_on=dep)
        print(f"\nChained after {dep}. If a training job fails, its dependent "
              "tests stay queued as DependencyNeverSatisfied -- scancel them.")

    elif args.job in ("test1", "test2"):
        test_job(args.job, passthrough, args, depends_on=args.after)


if __name__ == "__main__":
    main()
