"""Single entry point for the federated-EHR experiment: train and test jobs.

This is the only launcher. It submits SLURM jobs for the two things the paper
table needs -- training a regime (``train.py``) and scoring rare-code ML
efficacy across regimes (``test2_rare_efficacy.py``) -- and nothing else. Cohort
selection and freezing deliberately do NOT hang off this file: they run once,
produce a manifest that then never changes, and mixing a one-off data-prep step
into the launcher is how a "just rerun it" ends up silently re-splitting the
data underneath a half-finished comparison.

    # one training regime (submits, prints the job id)
    python examples/fedpyhealth/main.py train --regime fedavg --profile full

    # the whole table: four regimes, then Test 2 chained after they all finish
    python examples/fedpyhealth/main.py all --profile full \
        --cohort-file examples/fedpyhealth/cohorts/strat8.json

    # see the generated sbatch script without submitting anything
    python examples/fedpyhealth/main.py train --regime local --dry-run

Unrecognised flags pass straight through to the underlying script, so anything
``train.py`` or ``test2_rare_efficacy.py`` accepts still works::

    python examples/fedpyhealth/main.py train --profile full --n-rounds 100

Every job writes to ``_outputs/`` (gitignored): SLURM logs under
``_outputs/slurm/``, checkpoints and synthetic data under
``_outputs/<run_name>_save/``, one file per run under
``_outputs/results/runs/``, and test scores under ``_outputs/results/tests/``.
"""

import argparse
import os
import subprocess
import sys
from typing import List, Sequence, Tuple

from utils.cohort_io import DEFAULT_COHORT_FILE, load_manifest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SLURM_DIR = "_outputs/slurm"
LAUNCH_DIR = "_outputs/slurm/launch"

ACCOUNT = "bgyw-delta-gpu"
PARTITION = "gpuA100x4"
MAIL_USER = "zd16@illinois.edu"

REGIMES = ("fedavg", "fedavg_ft", "centralized", "local")

# Per-job resources. Both profiles load the FULL eICU (a tiny run is small in
# compute, not in data), so both need the same memory; only the wall clock
# differs. Tiny's own training is ~5-10 min, but the dataset load in front of it
# is the same fixed cost every run pays -- hence 2h rather than 20 minutes.
PROFILE_RESOURCES = {
    "tiny": {"time": "02:00:00", "mem": "128g"},
    "full": {"time": "48:00:00", "mem": "128g"},
}
# Test 1 only rebuilds frames and bootstraps; Test 2 trains a classifier per
# hospital per mask fold, so it gets the longer window.
TEST_RESOURCES = {
    "test1": {"time": "03:00:00", "mem": "128g"},
    "test2": {"time": "06:00:00", "mem": "128g"},
}

SBATCH_TEMPLATE = """#!/bin/bash
#SBATCH --mem={mem}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --partition={partition}
#SBATCH --account={account}
#SBATCH --job-name={job_name}
#SBATCH --time={time}
#SBATCH --gpus-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=closest
#SBATCH --mail-user={mail_user}
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output={slurm_dir}/%x-%j.out

# Generated by examples/fedpyhealth/main.py -- edit the launcher, not this file.
set -euo pipefail

source .venv/bin/activate

{command}
"""


def _build_arg_parser() -> argparse.ArgumentParser:
    # Shared flags live on a parent parser so they are accepted BOTH before and
    # after the subcommand. Defined only at the top level, `main.py train
    # --dry-run` would silently forward --dry-run to train.py and submit for
    # real. They default to SUPPRESS so an unset flag on the subparser does not
    # clobber the same flag given at the top level.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--dry-run", action="store_true",
                        default=argparse.SUPPRESS,
                        help="print the sbatch script(s) instead of submitting")
    common.add_argument("--time", default=argparse.SUPPRESS,
                        help="override the SBATCH wall clock")
    common.add_argument("--mem", default=argparse.SUPPRESS,
                        help="override the SBATCH memory")
    common.add_argument("--cohort-file", default=argparse.SUPPRESS,
                        help="frozen manifest every job in this invocation uses")
    common.add_argument("--skip-cohort-check", action="store_true",
                        default=argparse.SUPPRESS,
                        help="submit without pre-flighting the cohort file")

    p = argparse.ArgumentParser(
        description=__doc__ or "",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        parents=[common],
    )
    sub = p.add_subparsers(dest="job", required=True)

    train = sub.add_parser("train", parents=[common],
                           help="train one regime (train.py)")
    train.add_argument("--regime", choices=REGIMES, default="fedavg")
    train.add_argument("--profile", choices=sorted(PROFILE_RESOURCES),
                       default="full")

    every = sub.add_parser(
        "all", parents=[common],
        help="train all four regimes, then chain the tests after them")
    every.add_argument("--profile", choices=sorted(PROFILE_RESOURCES),
                       default="full")

    for name, helptext in (
        ("test1", "prevalence fidelity (test1_prevalence.py)"),
        ("test2", "pooled rare-code ML efficacy / TSTR (test2_rare_efficacy.py)"),
    ):
        t = sub.add_parser(name, parents=[common], help=helptext)
        t.add_argument("--after", default=None,
                       help="colon-separated job ids to wait for "
                            "(--dependency=afterok:...)")
    return p


def preflight_cohort(path: str) -> None:
    """Fail in a second, here, rather than an hour into a GPU job.

    The two failures this catches are the ones that cost the most: pointing at a
    ``*.cohort.json`` selection file (which names hospitals but assigns no
    patients), and pointing at a manifest frozen on the eICU dev subset, which
    ``train.py`` rejects only after it has loaded the whole dataset.
    """
    manifest = load_manifest(path)          # raises with a pointed message
    meta = manifest.get("meta", {})
    hospitals = manifest["hospitals"]
    n_train = sum(h["n_train"] for h in hospitals)
    n_val = sum(h["n_val"] for h in hospitals)

    if meta.get("dev"):
        sys.exit(
            f"{path} was frozen on the eICU DEV subset (meta.dev=true), but "
            "every profile runs on the full dataset. train.py would refuse the "
            "mismatch after loading eICU. Re-freeze without --dev."
        )

    print(f"cohort {meta.get('cohort_name', '?')} ({path})")
    print(f"  {len(hospitals)} hospitals, {n_train} train / {n_val} val "
          f"({n_val / max(1, n_train + n_val):.3f})")
    print(f"  ids: {', '.join(h['hospital_id'] for h in hospitals)}")


def with_cohort(passthrough: Sequence[str], cohort_file: str) -> List[str]:
    """Add ``--cohort-file`` unless the caller already passed one."""
    if any(a.startswith("--cohort-file") for a in passthrough):
        return list(passthrough)
    return list(passthrough) + ["--cohort-file", cohort_file]


# Knobs that change what a run *is*. train.py normally encodes these into the
# run name itself; since we pass an explicit --run-name, we have to fold any
# override back in, or two runs differing only in --n-rounds would share a name
# and clobber each other's checkpoints and results.
# --num-synth is deliberately NOT here. It changes only how many patients are
# generated from an already-trained model, so folding it into the name would
# fork the save dir and force a full retrain just to re-generate at a different
# count. Left out, a re-run with a bigger --num-synth finds the checkpoint,
# skips training entirely, and only regenerates. This also matches train.py's
# own make_run_name, which does not encode it either.
NAME_AFFECTING = ("--n-rounds", "--local-epochs", "--ft-epochs", "--weighting",
                  "--metrics")


def run_name_for(regime: str, profile: str, cohort_file: str,
                 passthrough: Sequence[str]) -> str:
    """Deterministic run name, so the launcher knows the save dir up front.

    Chaining the tests onto training requires knowing where the training run
    will put its output *before* it starts. train.py derives its own name from
    the resolved config, which the launcher cannot see, so the launcher supplies
    the name instead and both sides agree by construction.
    """
    cohort = os.path.splitext(os.path.basename(cohort_file))[0]
    name = f"{regime}_{profile}_{cohort}"
    for i, arg in enumerate(passthrough):
        if arg in NAME_AFFECTING and i + 1 < len(passthrough):
            name += f"_{arg.lstrip('-').replace('-', '')}{passthrough[i + 1]}"
        elif arg.startswith(tuple(f"{k}=" for k in NAME_AFFECTING)):
            key, val = arg.split("=", 1)
            name += f"_{key.lstrip('-').replace('-', '')}{val}"
    return name


def save_dir_for(run_name: str) -> str:
    """Where train.py will persist that run (must match train.py's save_dir)."""
    return f"_outputs/{run_name}_save"


def record_run(job_id: str, run_name: str, dry_run: bool) -> None:
    """Append the launched job to the experiment log.

    Done here because the launcher is the only place that knows both the job id
    and the run name; leaving it to the user means the log is only as complete
    as their discipline, which is exactly when a log stops being useful.
    """
    if dry_run or job_id == "DRYRUN":
        return
    try:
        subprocess.run(
            ["python", "examples/fedpyhealth/exp_log.py", "record",
             "--job-id", job_id, "--run-name", run_name],
            check=True, capture_output=True, text=True,
        )
        print(f"  logged {run_name} (job {job_id})")
    except Exception as exc:  # noqa: BLE001 - logging must never sink a launch
        print(f"  WARNING: could not log job {job_id}: {exc}. The job IS "
              f"submitted; record it by hand with exp_log.py record.")


def render(job_name: str, command: str, time: str, mem: str) -> str:
    """Fill the sbatch template for one job."""
    return SBATCH_TEMPLATE.format(
        mem=mem, partition=PARTITION, account=ACCOUNT, job_name=job_name,
        time=time, mail_user=MAIL_USER, slurm_dir=SLURM_DIR, command=command,
    )


def submit(job_name: str, script: str, dry_run: bool,
           depends_on: str = None) -> str:
    """Write the job script and submit it; return the job id ('DRYRUN' if not).

    The script is kept on disk under ``_outputs/slurm/launch/`` so a submitted
    job stays inspectable after the fact -- what actually ran, not what the
    launcher would generate today.
    """
    os.makedirs(SLURM_DIR, exist_ok=True)
    os.makedirs(LAUNCH_DIR, exist_ok=True)
    path = os.path.join(LAUNCH_DIR, f"{job_name}.sbatch")
    with open(path, "w") as fh:
        fh.write(script)

    cmd = ["sbatch", "--parsable"]
    if depends_on:
        cmd.append(f"--dependency=afterok:{depends_on}")
    cmd.append(path)

    if dry_run:
        print(f"--- {path}\n{script}")
        print(f"[dry-run] would run: {' '.join(cmd)}\n")
        return "DRYRUN"

    job_id = subprocess.check_output(cmd, text=True).strip()
    dep = f" (after {depends_on})" if depends_on else ""
    print(f"submitted {job_name}: job {job_id}{dep}  -> {SLURM_DIR}/{job_name}-{job_id}.out")
    return job_id


def train_job(regime: str, profile: str, passthrough: Sequence[str],
              args, cohort_file: str) -> Tuple[str, str]:
    """Submit one training regime. Returns ``(job_id, run_name)``."""
    res = PROFILE_RESOURCES[profile]
    run_name = run_name_for(regime, profile, cohort_file, passthrough)
    command = (f"python examples/fedpyhealth/train.py --profile {profile} "
               f"--regime {regime} --run-name {run_name} "
               f"{' '.join(passthrough)}").strip()
    script = render(
        job_name=f"fed-{regime}-{profile}",
        command=command,
        time=args.time or res["time"],
        mem=args.mem or res["mem"],
    )
    job_id = submit(f"fed-{regime}-{profile}", script, args.dry_run)
    record_run(job_id, run_name, args.dry_run)
    return job_id, run_name


def test_job(which: str, passthrough: Sequence[str], args,
             depends_on: str = None) -> str:
    """Submit a scoring job. ``which`` is ``test1`` or ``test2``."""
    script_name = {"test1": "test1_prevalence.py",
                   "test2": "test2_rare_efficacy.py"}[which]
    res = TEST_RESOURCES[which]
    command = (f"python examples/fedpyhealth/{script_name} "
               + " ".join(passthrough)).strip()
    script = render(
        job_name=f"fed-{which}",
        command=command,
        time=args.time or res["time"],
        mem=args.mem or res["mem"],
    )
    return submit(f"fed-{which}", script, args.dry_run, depends_on=depends_on)


def main(argv: List[str] = None) -> None:
    args, passthrough = _build_arg_parser().parse_known_args(argv)
    # SUPPRESS defaults mean an unset shared flag is simply absent.
    args.dry_run = getattr(args, "dry_run", False)
    args.time = getattr(args, "time", None)
    args.mem = getattr(args, "mem", None)
    cohort_file = getattr(args, "cohort_file", DEFAULT_COHORT_FILE)

    if os.path.abspath(os.getcwd()) != REPO_ROOT:
        sys.exit(f"run this from the repo root ({REPO_ROOT}) -- every path in "
                 "the generated job script is repo-relative")

    # A stray main.py flag reaching the training script means it was misparsed;
    # better to stop than to submit a job that dies on an unknown argument.
    stray = [a for a in passthrough
             if a in ("--dry-run", "--skip-cohort-check", "--time", "--mem")]
    if stray:
        sys.exit(f"internal: {stray} leaked into the job command -- refusing to "
                 "submit. This is a launcher bug, not a usage error.")

    if not getattr(args, "skip_cohort_check", False):
        preflight_cohort(cohort_file)
    passthrough = with_cohort(passthrough, cohort_file)

    if args.job == "train":
        train_job(args.regime, args.profile, passthrough, args, cohort_file)

    elif args.job == "all":
        submitted = [train_job(r, args.profile, passthrough, args, cohort_file)
                     for r in REGIMES]
        ids = [job_id for job_id, _ in submitted]
        dep = ":".join(ids)

        # Both tests read each run's synthetic.json, so they wait for all four.
        # The launcher assigned the run names, so it can build the --run specs
        # itself instead of asking the user to copy them out of four logs.
        run_specs: List[str] = []
        for (_, run_name), regime in zip(submitted, REGIMES):
            run_specs += ["--run", f"{regime}={save_dir_for(run_name)}"]
        print()
        for which in ("test1", "test2"):
            test_job(which, list(passthrough) + run_specs, args, depends_on=dep)
        print(f"\nChained after {dep}. If a training job fails, its dependent "
              "tests stay queued as DependencyNeverSatisfied -- scancel them.")

    elif args.job in ("test1", "test2"):
        test_job(args.job, passthrough, args, depends_on=args.after)


if __name__ == "__main__":
    main()
