#!/usr/bin/env python3
"""Expand a sweep ``grid.yaml`` into one config + one SLURM script per combo.

Reads a grid spec (a ``base:`` config + a ``grid:`` of lists), takes the
Cartesian product of the grid axes, overlays each combination on ``base:``, and
for every combination writes, under ``_outputs/sweeps/<sweep_name>/``:

  * ``configs/NNN.yaml``   -- a ready-to-run config (``train.py --config ...``)
  * ``jobs/NNN-<label>.sbatch`` -- a self-contained, individually launchable
    SLURM script for that one config (so each run is its own queue job you can
    squeue / scancel / resubmit on its own; they run in parallel)
  * ``submit_all.sh``      -- sbatch every job script in one go
  * ``runlist.txt``        -- one config path per line (for the array alternative)

Run names are auto-derived by ``train.py`` from each config's knobs, so per-run
artifacts + ``_outputs/results/<run_name>.json`` never collide.

Usage (from the repo root)::

    .venv/bin/python examples/fedpyhealth/sweeps/make_sweep.py \\
        examples/fedpyhealth/sweeps/grid.yaml

It prints how to submit (the per-job ``submit_all.sh``, or one array command).
"""
import itertools
import os
import shutil
import stat
import sys

import yaml

# SLURM resource block shared by every generated per-config job. Mirrors
# run_train_full.sh (single A100). Runtime ~ n_rounds * local_epochs; 18h
# covers the default grid's heaviest cell with margin.
SBATCH_TEMPLATE = """#!/bin/bash
#SBATCH --partition=gpuA100x4
#SBATCH --account=bgyw-delta-gpu
#SBATCH --job-name={jobname}
#SBATCH --time=18:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64g
#SBATCH --gpus-per-node=1
#SBATCH --mail-user=zd16@illinois.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --output=_outputs/slurm/%x-%j.out

# Auto-generated by make_sweep.py for sweep '{sweep_name}'. One config:
#   {config}
# Submit from the repo root:  sbatch {job_path}
set -euo pipefail
source .venv/bin/activate
python examples/fedpyhealth/train.py --config {config}
"""


def expand(spec: dict):
    """Yield (index, combo_tuple, config_dict) for every point in the grid."""
    base = spec.get("base", {}) or {}
    grid = spec.get("grid", {}) or {}
    keys = list(grid)
    axes = [grid[k] for k in keys]
    combos = list(itertools.product(*axes)) if keys else [()]
    for i, combo in enumerate(combos):
        cfg = dict(base)
        cfg.update({k: v for k, v in zip(keys, combo)})
        yield i, combo, cfg


def _make_executable(path: str):
    os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP)


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    grid_path = argv[0] if argv else "examples/fedpyhealth/sweeps/grid.yaml"
    with open(grid_path) as f:
        spec = yaml.safe_load(f) or {}

    sweep_name = spec.get("sweep_name", "sweep")
    sweep_dir = os.path.join("_outputs", "sweeps", sweep_name)
    cfg_dir = os.path.join(sweep_dir, "configs")
    job_dir = os.path.join(sweep_dir, "jobs")
    # Wipe any prior generation so a re-run with a smaller grid leaves no stale
    # configs/jobs behind (results.json lives elsewhere, under _outputs/results/).
    shutil.rmtree(cfg_dir, ignore_errors=True)
    shutil.rmtree(job_dir, ignore_errors=True)
    os.makedirs(cfg_dir, exist_ok=True)
    os.makedirs(job_dir, exist_ok=True)

    runlist, job_paths = [], []
    for i, combo, cfg in expand(spec):
        # Short, queue-readable label from the varying axes, e.g.
        # "000-fedavg-uniform-0.0003-2".
        label = "-".join(str(v) for v in combo) if combo else "run"
        jobname = f"{sweep_name}-{i:03d}-{label}"

        # CRITICAL: pin a unique run_name per combo. train.py's auto run_name only
        # encodes regime/E/R/cohort/metrics/weighting -- NOT lr or other swept
        # knobs -- so without this, two combos that differ only in (e.g.) lr would
        # share a run_name and clobber each other's results.json + checkpoints.
        cfg = dict(cfg)
        cfg["run_name"] = jobname

        cfg_path = os.path.join(cfg_dir, f"{i:03d}.yaml")
        with open(cfg_path, "w") as f:
            yaml.safe_dump(cfg, f, sort_keys=True)
        runlist.append(cfg_path)

        job_path = os.path.join(job_dir, f"{i:03d}-{label}.sbatch")
        with open(job_path, "w") as f:
            f.write(SBATCH_TEMPLATE.format(
                jobname=jobname, sweep_name=sweep_name,
                config=cfg_path, job_path=job_path))
        _make_executable(job_path)
        job_paths.append(job_path)

    runlist_path = os.path.join(sweep_dir, "runlist.txt")
    with open(runlist_path, "w") as f:
        f.write("\n".join(runlist) + "\n")

    submit_all = os.path.join(sweep_dir, "submit_all.sh")
    with open(submit_all, "w") as f:
        f.write("#!/bin/bash\n")
        f.write(f"# Submit every job in sweep '{sweep_name}' (run from repo root).\n")
        f.write("# Each is an independent SLURM job -> they run in parallel. Each\n")
        f.write("# submission is also recorded to the experiment log so a later\n")
        f.write("# `exp_log.py check` knows which jobs to look up + sweep.\n")
        f.write("set -euo pipefail\n")
        f.write("mkdir -p _outputs/slurm\n")
        for jp, cfg_path in zip(job_paths, runlist):
            # --parsable -> bare job id, so we can record (job_id, config) together.
            f.write(f'jid=$(sbatch --parsable {jp})\n')
            f.write(f'echo "submitted $jid  <-  {jp}"\n')
            f.write('.venv/bin/python examples/fedpyhealth/exp_log.py record '
                    f'--job-id "$jid" --config {cfg_path}\n')
    _make_executable(submit_all)

    n = len(job_paths)
    print(f"sweep '{sweep_name}': {n} runs")
    print(f"  configs -> {cfg_dir}")
    print(f"  jobs    -> {job_dir}  (one sbatch per run)")
    print()
    print("Launch all as separate parallel jobs (recommended):")
    print(f"  bash {submit_all}")
    print()
    print("Or as a single SLURM array (equivalent parallelism, one job id):")
    print(f"  mkdir -p _outputs/slurm")
    print(f"  sbatch --array=0-{n - 1} "
          f"examples/fedpyhealth/sweeps/run_sweep.sbatch {runlist_path}")


if __name__ == "__main__":
    main()
